name: Check Style Code for C# WPF

on:
    push:
        branches:
            - new_vetochka
    pull_request:
        branches:
            - new_vetochka

jobs:
    checkstyle:
        runs-on: windows-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 6.0

            - name: Restore dependencies
              run: dotnet restore

            - name: Run StyleCop Analyzers
              run: |
                dotnet tool install --global dotnet-format --version 5.1.250801
                dotnet format --verify-no-changes --verbosity diagnostic

